project:
  type: website
  output-dir: docs

website:
  title: "Between the moors and the sea"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/timbindingPCC/BetweenMoorsSea
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

