project:
  type: website
  output-dir: docs

website:
  title: "Between the moors and the sea"
  description: "A digital garden of sorts. Personal musings and ruminations"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/timbindingPCC/BetweenMoorsSea
      - text: Archive
        href: archive.qmd
  cookie-consent: true
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

